language: cpp
dist: precise
sudo: required

cache:
  directories:
  - deps
  - datasets

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python-numpy
  - sudo apt-get install -y -qq freeglut3 freeglut3-dev libxmu-dev libxi-dev

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - make toon
  - make eigen3
  - make suitesparse
  - make g2o
  - make cvd
  - make flann
  - make gvars
  - make freeimage
  - make pangolin
  - make opengv
  - make opencv
  - make brisk
  - make ceres
  - make pcl
  - make opentuner
  - ls deps
